### ISSUE TITLE
Addition of an output argument

### ISSUE THREAD

**Issue by aponsero** [KennthShang/PhaGCN#11]
Hello,

Thank you for developping PhaGCN, the tool was easy to install and super fast to run on viral sequences!
I however have some small suggestions in terms of usability of the tool:

- If I am not mistaken, the tool runs and creates outputs directly in the script folder. It would be amazing to be able to specify where the outputs of the tools should be created.
- Currently, when I need to re-running the tool several times on different datasets, I need to remove all the previous temporary outputs from the script folder before running the scripts.
- Similarly on an HPC system, the tool cannot be parrallelized as currently implemented, because all jobs needs to write in the script folder. 

My current implementation downloads the repo for each job, moves the contigs to classify in the script folder. Once the tool has run, I move outputs to the actual output location I need and delete the script repo. This is not unusable, but it probably could be improved.

**Comment by KennthShang** [comment]
Hi,

Thanks for using our tools. 

This current folder is the original code for PhaGCN described in the paper.

The latest version of PhaGCN is available via: https://github.com/KennthShang/PhaBOX, which meets your requirements.

Besides, we have also updated the latest ICTV taxa in the new version. Feel free to have a try.

Best,
Jiayu

**Comment by aponsero** [comment]
Perfect! Thanks!
