### ISSUE TITLE
Error Generating Knowledge graph

### ISSUE THREAD

**Issue by conchaeloko** [KennthShang/PhaGCN#2]
Hi Kenneth, 

I tried running the :``python run_Speed_up.py --contigs contigs.fa`` command and I got the following message error :
``---------------------------Generating Knowledge graph---------------------------``
``Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
GCN Error for file contig_0
cat: 'pred/*': No such file or directory
Traceback (most recent call last):
  File "run_Speed_up.py", line 150, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/home/user/anaconda3/envs/py3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.``

Have you got an idea about how it could be fixed ? 
Cheers,
Robby

**Comment by KennthShang** [comment]
It seems it is caused by your computer, not the program. Maybe you need to check whether your packages are all correct.

**Comment by conchaeloko** [comment]
I tried running the test command on a cluster and it actually worked. However, when I tried with the original data, I got another error message : 
```
``Reported 4347208 pairwise alignments, 4355711 HSPs.
284953 queries aligned.
folder Cyber_data/ exist... cleaning dictionary
Dictionary cleaned
rm: cannot remove ‘validation/*’: No such file or directory
rm: cannot remove ‘stride50_val/*’: No such file or directory
rm: cannot remove ‘int_val/*’: No such file or directory
rm: cannot remove ‘filtered_val/*’: No such file or directory
rm: cannot remove ‘dataset/*’: No such file or directory
rm: cannot remove ‘split_long_reads_val/*’: No such file or directory
Capturing compressed features
/home/user/.conda/envs/py3.6/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370116979/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Running with cpu
rm: cannot remove ‘validation/*’: No such file or directory
rm: cannot remove ‘stride50_val/*’: No such file or directory
rm: cannot remove ‘int_val/*’: No such file or directory
rm: cannot remove ‘filtered_val/*’: No such file or directory
rm: cannot remove ‘dataset/*’: No such file or directory
rm: cannot remove ‘split_long_reads_val/*’: No such file or directory
folder out/ exist... cleaning dictionary
Dictionary cleaned
folder single_contig/ exist... cleaning dictionary
folder all_proteins/ exist... cleaning dictionary
cat: all_proteins/*: No such file or directory
Traceback (most recent call last):
  File "run_KnowledgeGraph.py", line 126, in <module>
    _ = subprocess.check_call("cat {0} > {1}".format(file_out_fn+"*", all_protein_f), shell=True)
  File "/home/user/.conda/envs/py3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat all_proteins/* > out/all_translate_proteins.fa' returned non-zero exit status 1.
Knowledge Graph Error for file contig_0
cat: pred/*: No such file or directory
Traceback (most recent call last):
  File "run_Speed_up.py", line 150, in <module>
    out = subprocess.check_call(cmd, shell=True)
  File "/home/user/.conda/envs/py3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.
```

I tried moving the data to the same repository as the other PhaGCN files but it did not fix it. Do you have an insights ?

Cheers,
Robby

**Comment by KennthShang** [comment]
What do you mean "on a cluster it works" and "the original data has the error". 
Do you mean you the PhaGCN can be run correctly on a HPC but cannot be run your computer?
And what is the original data? Do you mean the given "contig.fa"?

**Comment by conchaeloko** [comment]
Hi Kennth, 
My bad, my message as unclear : I ran the `python run_Speed_up.py --contigs contigs.fa` on a HPC and it worked i.e I got the output "final_prediction.csv" with taxonomic information for each contig. But when I tried the same command on my own data (a set of 300 phages), the process stopped with the error message copied in my previous comment.

**Comment by KennthShang** [comment]
That's weird.  Did you check whether your dataset has the same format as 'contigs.fa'? Or did you pass the correct 'path' of your dataset to the program? 

Because it outputted 'cat: all_proteins/*: No such file or directory', which means it cannot convert your contigs into proteins. A simple way to check it out is to rename your contigs file as 'contigs.fa' and put it into the same path as the old 'contigs.fa'. 

Hope this will help you to solve your problem

**Comment by palomo11** [comment]
> Hi Kenneth,
> 
> I tried running the :`python run_Speed_up.py --contigs contigs.fa` command and I got the following message error :
> `---------------------------Generating Knowledge graph---------------------------`
> `Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library. Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it. GCN Error for file contig_0 cat: 'pred/*': No such file or directory Traceback (most recent call last): File "run_Speed_up.py", line 150, in <module> out = subprocess.check_call(cmd, shell=True) File "/home/user/anaconda3/envs/py3.6/lib/python3.6/subprocess.py", line 291, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command 'cat pred/* > final_prediction.csv' returned non-zero exit status 1.`
> 
> Have you got an idea about how it could be fixed ?
> Cheers,
> Robby

Hi Robby,

I am having the same issue. How did you solve it?

Thanks in advance!

**Comment by KennthShang** [comment]
Hey guys,

If you still have not solved the bug. And if it is available, you can email me some small samples of your dataset for debugging.

Best,
Jiayu

**Comment by palomo11** [comment]
I just solved it.

I have to do: 
export MKL_SERVICE_FORCE_INTEL=1

then run PhaGCN:
python run_Speed_up.py --contigs contigs.fa

**Comment by KennthShang** [comment]
Great job! Nice to hear that.
