### ISSUE TITLE
mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library. 

### ISSUE THREAD

**Issue by marineLZ** [KennthShang/PhaGCN#5]
Dear  authours, thank  you for  your  excellent  work.

I have  added  command export MKL_SERVICE_FORCE_INTEL=1，but errors still occur :
mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library. 

But  I get  the final  result :  final_prediction.csv .

Is this normal? Does it affect the accuracy of the results?

**Comment by KennthShang** [comment]
Since I have not seen this error on my test machines, i don't know whether it will affect the predictions. But i think it is ok according to the issue link: https://github.com/pytorch/pytorch/issues/37377

Best,
Jiayu
