### ISSUE TITLE
How to run PhaGCN on multiple fasta files? For example multiple viral MAGs? 

### ISSUE THREAD

**Issue by JSSaini** [KennthShang/PhaGCN#6]

**Comment by KennthShang** [comment]
You can write a script to run the PhaGCN iteratively.  if you are using python, a simple script can be:
```
    import os
    
    for file in os.listdir('folder/'):
        os.system(f'python run_Speed_up.py --contigs folder/{file} -len 8000')
```
'folder/' is the folder of your files.

Or maybe you can use '[cat](https://www.geeksforgeeks.org/cat-command-in-linux-with-examples/)' function to combine your fasta files into one file.

**Comment by JSSaini** [comment]
Thank you for your prompt reply. This will give single-output (final_prediction.csv) for each folder or multiple outputs for each bin within the folder? Is it possible to get out the output (final_prediction.csv) respective input folder/file/viral mag name? 

I wanted to have taxonomy on each viral bin that's why I was preventing "cat".

**Comment by KennthShang** [comment]
ah, i see what you mean. Since the program will ouput a label for each sequence, even though you place the sequence of a bin in one files, it will separate them individually. 

I am sorry that PhaGCN cannot handle this case (treat a bin as one genome). Alternatively, you can predict all the sequences in a bin and use majority vote on the final prediction for the bin. 

Best,
Jiayu

**Comment by JSSaini** [comment]
Thank you for answering my queries. One last question. Is there any way to known how many sequences were taxonomically assigned from the input file. For example: In case I input one fasta file obtained using Deepvirfinder and assign the taxonomy using PhaGCN. How would I know what % of sequences the phage taxonomy was assigned? and/or how many sequences had no taxonomy? Is there a script/function to do that using PhaGCN? Thanks a lot for your suggestions.

**Comment by KennthShang** [comment]
I think this can be done with the code below:

'''
        from Bio import SeqIO
        import pandas as pd
        # the original file
        print(len(list(SeqIO.parse('input.fa', 'fasta'))))
        # PhaGCN file
        print(len(pd.read_csv('final_prediction.csv')))
'''

Also, it is count for sequences not for bins, for bins you need to have a dict to show which seqs should be in the same bin

(Since I type this with my phone, maybe there is typo of the script.)

Best,
Jiayu

**Comment by JSSaini** [comment]
Yes I am trying on one Deepvirfinder fasta file not multiple bins. 
 
Sorry, I am new to python scripting. Is it possible to get the output result in text/csv file?

**Comment by JSSaini** [comment]
You may also close the issue. Thank you for the awesome tool.
