### ISSUE TITLE
Can it be used on human gut metagenome?

### ISSUE THREAD

**Issue by PB-Shinde** [KennthShang/PhaGCN#7]
Hello, I would like to know if we can use this tool on Human gut metagenome as you tested this tool on oyster metagenome. I would like to know if database is appropriate for human gut.

Thank you.

**Comment by KennthShang** [comment]
Hi,

Sure, PhaGCN can be applied to any kind of dataset if you want to classify phages. 

We use oyster metagenomic data as an example in the paper because one of the authors sampled them from the marine.

Best,
Jiayu

**Comment by PB-Shinde** [comment]
Thank you
